apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dns-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0" # apply before database
spec:
  project: default
  destination:
    namespace: dns-system
    name: in-cluster
  sources:
    - repoURL: 'https://github.com/LeegacySystem/homelab-configurations'
      path: configs/pdns-server
      targetRevision: feature/restructure
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true