---
apiVersion: v1
kind: Namespace
metadata:
  name: dns-system
---
# Source: powerdns/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdns-server
  namespace: dns-system
  labels:
    app: pdns-server
    component: pdns-authoritative
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdns-server
      component: pdns-authoritative
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pdns-server
        component: pdns-authoritative
    spec:
      nodeSelector:
        node-type: opt # distributed storage saves having to setup db
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - opt
      #serviceAccountName: powerdns
      securityContext:
        # This limited config did not work, will revisit
        # fsGroup: 953
      containers:
        - name: pdns-server
          securityContext:
            # This limited config did not work, will revisit or use higher ports
            # capabilities:
            #   add: ["NET_BIND_SERVICE"]
            # allowPrivilegeEscalation: true
            runAsUser: 0
          image: "powerdns/pdns-auth-49:4.9.2"
          imagePullPolicy: Always
          env:
          - name: PDNS_AUTH_API_KEY
            valueFrom:
              secretKeyRef:
                name: pdns-auth-api-key-secret
                key: PDNS_AUTH_API_KEY
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: webserver
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: dns-tcp
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10

          readinessProbe:
            tcpSocket:
              port: webserver
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10

          volumeMounts:
          - name: pdns-auth-config-volume
            mountPath: /etc/powerdns/pdns.conf
            subPath: pdns.conf
          
          resources:
            {}
      volumes:
      - name: pdns-auth-config-volume
        configMap:
          name: pdns-server-config
