---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" # apply after server
spec:
  project: default
  destination:
    namespace: dns-system
    name: in-cluster
  sources:
    # - repoURL: https://kubernetes-sigs.github.io/external-dns/
    #   chart: external-dns
    #   targetRevision: '1.15.0'
    #   directory:
    #     include: 'external-dns.yml'
    #   helm:
    #     parameters:
    #       - name: sources[0]
    #         value: ingress
    #       - name: provider.name
    #         value: 'pdns'
    #       - name: provider.pdns.server
    #         value: 'pdns-metrics.dns-system'
    #       - name: extraArgs[0]
    #         value: --pdns-server=http://pdns-metrics.dns-system:8081
    #       # - name: extraArgs[1]
    #       #   value: --pdns-api-key=test123
    #       # - name: provider.pdns.api-key
    #       #   valueFrom:
    #       #     secretKeyRef:
    #       #       name: pdns-auth-api-key-secret
    #       #       key: PDNS_AUTH_API_KEY 
    #       # - name: domainFilters
    #       #   valueFrom:
    #       #     secretKeyRef:
    #       #       name: external-dns-domain
    #       #       key: domain
    #       - name: extraArgs[1]
    #         value: --pdns-api-key=$(PDNS_API_KEY)
    #       - name: extraArgs[2]
    #         value: --domain-filter=$(DOMAIN_FILTER)
    #       - name: env[0].name
    #         value: PDNS_API_KEY
    #       - name: env[0].valueFrom.secretKeyRef.name
    #         value: pdns-auth-api-key-secret
    #       - name: env[0].valueFrom.secretKeyRef.key
    #         value: PDNS_AUTH_API_KEY
    #       - name: env[1].name
    #         value: DOMAIN_FILTER
    #       - name: env[1].valueFrom.configMapKeyRef.name
    #         value: external-dns-domain
    #       - name: env[1].valueFrom.configMapKeyRef.key
    #         value: domain
    - repoURL: 'https://github.com/LeegacySystem/homelab-configurations'
      path: configs/pdns-server
      targetRevision: HEAD
      directory:
        include: 'external-dns.yml'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true