apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pdns-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # apply before database
spec:
  project: default
  destination:
    namespace: dns-system
    name: in-cluster
  sources:
    - repoURL: 'https://github.com/LeegacySystem/homelab-applications'
      directory:
        include: 'pdns-server-manifest.yml'
      path: main-apps/dns
      targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true