apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pdns-server
  namespace: argocd
spec:
  project: default
  destination:
    namespace: dns-system
    name: in-cluster
  sources:
    - repoURL: 'https://github.com/LeegacySystem/homelab-configurations'
      path: configs/pdns-server
      targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true