apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-debugger
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/LeegacySystem/empty.git' # Replace with an empty repo or sample repo
    path: "" # Blank path if it's an empty repo
    targetRevision: HEAD
    helm:
      values: |
        replicaCount: 1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dns-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-debugger
  namespace: dns-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-debugger
  template:
    metadata:
      labels:
        app: network-debugger
    spec:
      containers:
        - name: network-debugger
          image: nicolaka/netshoot:latest # Useful for debugging as it includes many network tools
          command: ["/bin/sh", "-c", "while true; do sleep 3600; done"] # Keeps the pod running
          env:
            - name: PDNS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: pdns-auth-api-key-secret  # Replace with the name of your PDNS API key secret
                  key: PDNS_AUTH_API_KEY
            - name: PDNS_SERVER
              value: "http://pdns-metrics.dns-system:8081"  # URL to your PDNS server
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
