apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-ingress
  namespace: argocd
spec:
  project: default
  destination:
    namespace: traefik-system
    name: in-cluster
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: '32.1.1'
      helm:
        parameters:
          - name: service.enabled
            value: 'false'
          - name: commonLabels.app
            value: "traefik-external"
          - name: globalArguments
            value: "--global.checknewversion"
    - repoURL: 'https://github.com/LeegacySystem/homelab-configurations'
      path: configs/traefik-external
      targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true