apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefiik
  namespace: argocd
spec:
  project: default
  destination:
    namespace: traefik-v2
    name: in-cluster
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: '32.1.1'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: "" # do not deploy default service
      kind: Service
      name: traefiik-traefik
      namespace: traefik-v2