apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  destination:
    namespace: monitoring
    name: in-cluster
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: '8.5.8'
    - repoURL: 'https://github.com/LeegacySystem/homelab-configurations'
      path: configs/grafana
      targetRevision: feature/restructure
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true