apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-ingresses
  namespace: argocd
spec:
  project: default
  destination:
    namespace: traefik-system
    name: in-cluster
  sources:
    - repoURL: 'https://github.com/LeegacySystem/homelab-configurations'
      path: configs/core-ingresses
      targetRevision: feature/restructure  # HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true