apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  destination:
    namespace: longhorn-system
    name: in-cluster
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: '1.7.2'
      helm:
        parameters:
          - name: global.nodeSelector.node-type
            value: "opt"
          - name: preUpgradeChecker.jobEnabled
            value: "false"
          - name: defaultSettings.logLevel
            value: "Debug"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true