apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  destination:
    namespace: metallb-system
    name: in-cluster
  sources:
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: '0.14.7'
    - repoURL: 'https://github.com/LeegacySystem/homelab-configurations'
      path: configs/metallb_config.yml
      targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle