apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-apps
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: main-apps/cert-manager
    repoURL: 'https://github.com/LeegacySystem/homelab-applications'
    targetRevision: HEAD
  project: default
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true