apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-apps
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: main-apps/core-apps
    repoURL: 'https://github.com/LeegacySystem/homelab-applications'
    targetRevision: feature/app-restructure  # HEAD
  project: default
