apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: main-apps/monitoring
    repoURL: 'https://github.com/LeegacySystem/homelab-applications'
    targetRevision: HEAD
  project: default
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true